# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(820, 405)
        Form.setMinimumSize(QtCore.QSize(805, 405))
        Form.setMaximumSize(QtCore.QSize(820, 405))
        Form.setStyleSheet(".QWidget {\n"
"   background-color: beige;\n"
"}\n"
"\n"
"/* Nice Windows-XP-style password character. */\n"
"QLineEdit[echoMode=\"2\"] {\n"
"    lineedit-password-character: 9679;\n"
"}\n"
"\n"
"/* We provide a min-width and min-height for push buttons\n"
"   so that they look elegant regardless of the width of the text. */\n"
"QPushButton {\n"
"    background-color: palegoldenrod;\n"
"    /*border-width: 2px;*/\n"
"    /*border-color: darkkhaki;*/\n"
"    /*border-style: solid;*/\n"
"    border-radius: 5;\n"
"    padding: 3px;\n"
"    min-width: 9ex;\n"
"    min-height: 2.5ex;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background-color: khaki;\n"
"}\n"
"\n"
"/* Increase the padding, so the text is shifted when the button is\n"
"   pressed. */\n"
"QPushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: #d0d67c;\n"
"}\n"
"\n"
"QLabel, QAbstractButton {\n"
"    font: bold;\n"
"}\n"
"\n"
"/* Mark mandatory fields with a brownish color. */\n"
".mandatory {\n"
"    color: brown;\n"
"}\n"
"\n"
"/* Bold text on status bar looks awful. */\n"
"QStatusBar QLabel {\n"
"   font: normal;\n"
"}\n"
"\n"
"QStatusBar::item {\n"
"    border-width: 0;\n"
"   /* border-color: darkkhaki;*/\n"
"    /*border-style: solid;*/\n"
"    border-radius: 2;\n"
"}\n"
"\n"
"QComboBox, QLineEdit, QSpinBox, QTextEdit, QListView {\n"
"    background-color: cornsilk;\n"
"    selection-color: #0a214c; \n"
"    selection-background-color: #C19A6B;\n"
"}\n"
"\n"
"QListView {\n"
"    show-decoration-selected: 1;\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"    background-color: wheat;\n"
"}\n"
"\n"
"/* We reserve 1 pixel space in padding. When we get the focus,\n"
"   we kill the padding and enlarge the border. This makes the items\n"
"   glow. */\n"
"QLineEdit, QFrame {\n"
"    /*border-width: 2px;*/\n"
"    padding: 1px;\n"
"    /*border-style: solid;*/\n"
"    /*border-color: darkkhaki;*/\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/* As mentioned above, eliminate the padding and increase the border. */\n"
"QLineEdit:focus, QFrame:focus {\n"
"    /*border-width: 3px;*/\n"
"    padding: 0px;\n"
"}\n"
"\n"
"/* A QLabel is a QFrame ... */\n"
"QLabel {\n"
"    border: none;\n"
"    padding: 0;\n"
"    background: none;\n"
"}\n"
"\n"
"/* A QToolTip is a QLabel ... */\n"
"QToolTip {\n"
"    /*border: 2px solid darkkhaki;*/\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"    opacity: 200;\n"
"}\n"
"\n"
"/* Nice to have the background color change when hovered. */\n"
"QRadioButton:hover, QCheckBox:hover {\n"
"    background-color: wheat;\n"
"}\n"
"\n"
"/* Force the dialog\'s buttons to follow the Windows guidelines. */\n"
"QDialogButtonBox {\n"
"    button-layout: 0;\n"
"}\n"
"QTabBar {\n"
"    qproperty-drawBase: 0;\n"
"    left: 5px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTabBar:focus {\n"
"    border: 0px transparent black;\n"
"}\n"
"\n"
"QTabBar::close-button {\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    border-radius: 2px;\n"
"    background-image: url(icons/close_dark.png);\n"
"    background-position: center center;\n"
"    background-repeat: none;\n"
"}\n"
"\n"
"QTabBar::close-button:hover {\n"
"    background-color: #7cabf9;\n"
"}\n"
"\n"
"QTabBar::close-button:pressed {\n"
"    background-color: #adc5ed;\n"
"}\n"
"\n"
"QTabBar::scroller { /* the width of the scroll buttons */\n"
"    width: 20px;\n"
"}\n"
"\n"
"/* the scroll buttons are tool buttons */\n"
"QTabBar QToolButton,\n"
"QTabBar QToolButton:hover { \n"
"    margin-top: 4px;\n"
"    margin-bottom: 4px;\n"
"    margin-left: 0px;\n"
"    margin-right: 0px;\n"
"    padding: 0px;\n"
"    border: none;\n"
"    background-color: #e6e6e6;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:enabled {\n"
"     image: url(icons/right_arrow_light.png);\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:disabled,\n"
"QTabBar QToolButton::right-arrow:off {\n"
"     image: url(icons/right_arrow_disabled_dark.png);\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:hover {\n"
"     image: url(icons/right_arrow_lighter.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::left-arrow:enabled {\n"
"     image: url(icons/left_arrow_light.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::left-arrow:disabled,\n"
" QTabBar QToolButton::left-arrow:off {\n"
"     image: url(icons/left_arrow_disabled_dark.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::left-arrow:hover {\n"
"     image: url(icons/left_arrow_lighter.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::up-arrow:enabled {\n"
"     image: url(icons/up_arrow_light.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::up-arrow:disabled,\n"
" QTabBar QToolButton::up-arrow:off {\n"
"     image: url(icons/up_arrow_disabled_dark.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::up-arrow:hover {\n"
"     image: url(icons/up_arrow_lighter.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::down-arrow:enabled {\n"
"     image: url(icons/down_arrow_light.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::down-arrow:disabled,\n"
" QTabBar QToolButton::down-arrow:off {\n"
"     image: url(icons/down_arrow_disabled_dark.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::down-arrow:hover {\n"
"     image: url(icons/down_arrow_lighter.png);\n"
"}\n"
"\n"
"/* TOP and BOTTOM TABS */\n"
"QTabBar::tab:top,\n"
"QTabBar::tab:bottom {\n"
"    color: #ffffff;\n"
"    border: 1px solid #b6b6b6;\n"
"    border-left-color: #e6e6e6;\n"
"    border-right-width: 0px;\n"
"    background-color: #b6b6b6;\n"
"    padding:5px 15px;\n"
"    margin-top: 4px;\n"
"    margin-bottom: 4px;\n"
"    position: center;\n"
"}\n"
"\n"
"QTabBar::tab:top:first,\n"
"QTabBar::tab:bottom:first {\n"
"    border-top-left-radius: 6px;\n"
"    border-bottom-left-radius: 6px;\n"
"}\n"
"\n"
"QTabBar::tab:top:last,\n"
"QTabBar::tab:bottom:last {\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    border-right-width: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected,\n"
"QTabBar::tab:bottom:selected {\n"
"    color: black;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #3874f2, stop:1 #5e90fa);\n"
"    border-color: #3874f2;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected:hover,\n"
"QTabBar::tab:bottom:!selected:hover {\n"
"    color: black;\n"
"}\n"
"\n"
"QTabBar::tab:top:only-one ,\n"
"QTabBar::tab:bottom:only-one {\n"
"    border: 1px solid #1b3774;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"/* LEFT and RIGHT TABS */\n"
"QTabBar::tab:left,\n"
"QTabBar::tab:right {\n"
"    color: #ffffff;\n"
"    border: 1px solid #b6b6b6;\n"
"    border-top-color: #e6e6e6;\n"
"    border-bottom-width: 0px;\n"
"    background-color: #b6b6b6;\n"
"    padding: 15px 5px;\n"
"    margin-left: 4px;\n"
"    margin-right: 4px;\n"
"    position: center;\n"
"}\n"
"\n"
"QTabBar::tab:left:first,\n"
"QTabBar::tab:right:first {\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"}\n"
"\n"
"QTabBar::tab:left:last,\n"
"QTabBar::tab:right:last {\n"
"    border-bottom-left-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    border-bottom-width: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected,\n"
"QTabBar::tab:right:selected {\n"
"    color: black;\n"
"    background-color: qlineargradient(spread:pad, x1:0.545, y1:1, x2:0, y2:1, stop:0 #3874f2, stop:1 #5e90fa);\n"
"    border-color: #3874f2;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected:hover,\n"
"QTabBar::tab:right:!selected:hover {\n"
"    color: black;\n"
"}\n"
"\n"
"QTabBar::tab:left:only-one ,\n"
"QTabBar::tab:right:only-one {\n"
"    border: 1px solid #1b3774;\n"
"    border-radius: 6px;\n"
"}\n"
"QComboBox {\n"
"    color: #ffffff;\n"
"    background-color: #b6b6b6;\n"
"    selection-color: black;\n"
"    selection-background-color: #5e90fa;\n"
"    border: 1px solid #b6b6b6; /* border top color defined after QAbstractSpinBox, QLineEdit and QComboBox */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    color: black;\n"
"    background-color: #b6b6b6;\n"
"    border-color: #7cabf9;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: transparent;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.8, x2:1, y2:0, stop:0 #5e90fa, stop:1 #7cabf9);\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(icons/down_arrow_light.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on,\n"
"QComboBox::down-arrow:hover,\n"
"QComboBox::down-arrow:focus {\n"
"    image: url(icons/down_arrow_lighter.png);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color: #ffffff;\n"
"    background-color: #828282;\n"
"    border-radius: 3px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Common parameters for QAbstractSpinBox, QLineEdit and QComboBox */\n"
"QSpinBox,\n"
"QDoubleSpinBox,\n"
"QAbstractSpinBox,\n"
"QLineEdit,\n"
"QComboBox {\n"
"    border-top-color: #a2a2a0; /* Creates an inset effect inside the elements */\n"
"    padding: 2px 6px 2px 6px; /* This makes text colour work on QComboBox */\n"
"    margin: 0px 2px 0px 2px;\n"
"    min-width: 70px; /* it was 120 because of QCombobox... */\n"
"    border-radius: 3px;\n"
"}")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 9, 800, 400))
        self.frame.setMinimumSize(QtCore.QSize(800, 400))
        self.frame.setMaximumSize(QtCore.QSize(800, 400))
        self.frame.setStyleSheet("font: 18pt \"Shorooq_N1\";")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(366, 0, 101, 31))
        self.label.setStyleSheet("background-color: rgb(237, 216, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 40, 811, 351))
        self.frame_2.setStyleSheet("font: 14pt \"Shorooq_N1\";\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(700, 40, 91, 20))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(500, 40, 181, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(260, 40, 91, 20))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(170, 40, 86, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 90, 811, 181))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(720, 130, 51, 20))
        self.label_9.setObjectName("label_9")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_2.setGeometry(QtCore.QRect(560, 121, 101, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(710, 30, 61, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(360, 30, 51, 20))
        self.label_11.setObjectName("label_11")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(570, 30, 91, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(250, 30, 91, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 120, 121, 31))
        self.pushButton_2.setStyleSheet("background-color: rgb(110, 158, 249);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(240, 120, 111, 31))
        self.pushButton.setStyleSheet("background-color: rgb(110, 158, 249);")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(706, 3, 61, 20))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 0, 60, 31))
        self.pushButton_3.setStyleSheet("background-color: rgba(255, 255, 255, 10);")
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/blue/icons/x-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "إضافة كمية"))
        self.label_2.setText(_translate("Form", "كود / الصنف"))
        self.label_4.setText(_translate("Form", "الكمية /العدد"))
        self.lineEdit_3.setText(_translate("Form", "0"))
        self.label_9.setText(_translate("Form", "المخزن"))
        self.label_10.setText(_translate("Form", "سعر شراء "))
        self.label_11.setText(_translate("Form", "سعر بيع"))
        self.pushButton_2.setText(_translate("Form", "حفظ وإضافة جديد"))
        self.pushButton.setText(_translate("Form", "حفظ وإغلاق"))
import resources_rc
